### ISSUE TITLE
Run examples

### ISSUE THREAD

**Issue by orsinium** [agnivade/wasmbrowsertest#14]
Is it possible to run examples?

```go
package js_test

import "syscall/js"

func ExampleConsole() {
	console := js.Global().Get("console")
	console.Call("log", "1")
	// Output: 3
}
```

```
testing: open temp file: open /tmp/go-example-stdout-ExampleConsole-0.txt: not implemented on js
exit status 1
```

Can we make it not to redirect the output in a file? Or maybe make our own hack to check the stdout output?

**Comment by Gregory-Ledray** [comment]
I'm kind of confused. What's your goal? If you're trying to do a 'hello world' example in WASM, why not compile it with `go build` and serve the relevant directory as explained in the [getting started](https://github.com/golang/go/wiki/WebAssembly#getting-started)? wasmbrowsertest has hard-coded an index.html file and pulls in wasm_exec.js from misc/wasm/wasm_exec.js so IMO it's not a good choice for experimenting with WASM, since you won't be able to write your own HTML, CSS or JS without modifying wasmbrowsertest itself.

If your goal is to write a test, I would suggest importing testing and using fmt or another package to print to console.
```
package js_test

import (
        "syscall/js"
        "testing"
)

func TestExampleConsole(t *testing.T) {
        console := js.Global().Get("console")
        console.Call("log", "1")
        // Output: 3
        t.Fatal("test finished")
}
```
output on WSL:
```
greg@LAPTOP-AH6IAHBO:~/orsinium-test$ GOOS=js GOARCH=wasm go test -tags=integration -exec=/home/greg/test-build-wasm-6/wasmbrows
ertest/wasmbrowsertest ./...
1
--- FAIL: TestExampleConsole (0.00s)
    example_test.go:12: test finished
FAIL
[wasmbrowsertest]: 2020/02/09 10:08:18 main.go:161: context deadline exceeded
FAIL    _/home/greg/orsinium-test       6.817s
FAIL
```

If your goal is to mess with wasmbrowsertest, this is the output when I output the browser logs on what you wrote:
```
greg@LAPTOP-AH6IAHBO:~/orsinium-test$ GOOS=js GOARCH=wasm go test -tags=integration -exec=/home/greg/test-build-wasm-6/wasmbrows
ertest/wasmbrowsertest ./...
testing: open temp file: open /tmp/go-example-stdout-ExampleConsole-0.txt: not implemented on js
[wasmbrowsertest]: 2020/02/09 09:51:12 main.go:221: console logged: {"type":"log","args":[{"type":"string","value":"testing: ope
n temp file: open /tmp/go-example-stdout-ExampleConsole-0.txt: not implemented on js"}],"executionContextId":2,"timestamp":15812
63472361,"stackTrace":{"callFrames":[{"functionName":"writeSync","scriptId":"3","url":"http://localhost:56727/wasm_exec.js","lin
eNumber":40,"columnNumber":13},{"functionName":"write","scriptId":"3","url":"http://localhost:56727/wasm_exec.js","lineNumber":4
9,"columnNumber":19},{"functionName":"syscall/js.valueCall","scriptId":"3","url":"http://localhost:56727/wasm_exec.js","lineNumb
er":326,"columnNumber":30},{"functionName":"","scriptId":"5","url":"","lineNumber":1251,"columnNumber":960212},{"functionName":"
","scriptId":"5","url":"","lineNumber":1237,"columnNumber":951349},{"functionName":"","scriptId":"5","url":"","lineNumber":1291,
"columnNumber":984110},{"functionName":"","scriptId":"5","url":"","lineNumber":1287,"columnNumber":979528},{"functionName":"","s
criptId":"5","url":"","lineNumber":1374,"columnNumber":1065394},{"functionName":"","scriptId":"5","url":"","lineNumber":1397,"co
lumnNumber":1079084},{"functionName":"","scriptId":"5","url":"","lineNumber":2016,"columnNumber":1509203},{"functionName":"","sc
riptId":"5","url":"","lineNumber":2172,"columnNumber":1708965},{"functionName":"","scriptId":"5","url":"","lineNumber":2171,"col
umnNumber":1707058},{"functionName":"","scriptId":"5","url":"","lineNumber":2163,"columnNumber":1694506},{"functionName":"","scr
iptId":"5","url":"","lineNumber":2191,"columnNumber":1734564},{"functionName":"","scriptId":"5","url":"","lineNumber":954,"colum
nNumber":821641},{"functionName":"","scriptId":"5","url":"","lineNumber":952,"columnNumber":821596},{"functionName":"run","scrip
tId":"3","url":"http://localhost:56727/wasm_exec.js","lineNumber":474,"columnNumber":22},{"functionName":"","scriptId":"4","url"
:"http://localhost:56727/","lineNumber":60,"columnNumber":12}]}}
FAIL    _/home/greg/orsinium-test       1.739s
FAIL
```

**Comment by orsinium** [comment]
Hi, thank you for your reply. I'm making a library for WASM, and I was thinking about the `Example` mechanism since it's the fast and simple way to check some complex JS objects.

```js
$ obj = {a:1}
{a: 1}
$ obj.toString()
"[object Object]"
$ console.dir(obj)
Object
  a: 1
```

JS console gives enough features to inspect the object but I don't know how to get the full representation of an object from Go. There is [vert](https://github.com/norunners/vert) but you have to know and specify the expected object structure before.

**Comment by Gregory-Ledray** [comment]
You can use a Go library which pretty-prints Go structures recursively. All of the print statements in Go programs should be getting logged to console.

[From here](https://github.com/avelino/awesome-go) I found this: https://github.com/davecgh/go-spew

Code:
```
package js_test

import (
        "syscall/js"
        "testing"
        "github.com/davecgh/go-spew/spew"
)

type alpha struct {
        aField string
}

func TestExampleConsole(t *testing.T) {
        console := js.Global().Get("console")
        console.Call("log", "1")
        // Output: 3
        someStruct := alpha{
                aField: "field 1's value",
        }
        spew.Dump(someStruct)
        t.Fatal("test finished")
}
```
Output:
```
greg@LAPTOP-AH6IAHBO:~/orsinium-test$ GOOS=js GOARCH=wasm go test -tags=integration -exec=/home/greg/test-build-wasm-6/wasmbrows
ertest/wasmbrowsertest ./...
1
(js_test.alpha) {
 aField: (string) (len=15) "field 1's value"
}
--- FAIL: TestExampleConsole (0.02s)
    example_test.go:21: test finished
FAIL
[wasmbrowsertest]: 2020/02/09 12:36:38 main.go:161: context deadline exceeded
FAIL    example.com/hi  16.348s
FAIL
```

**Comment by agnivade** [comment]
There is no file io support because the browser doesnt support it yet. I have created an issue on puppetteer, but its not being worked on yet.

**Comment by orsinium** [comment]
@Gregory-Ledray we still have to provide a Go struct with specified fields to get a JS object. If we don't know all the fields of the object, we can't map it on Go struct. Probably, there is a way to enumerate all object's fields and so put them on Go's `map` but I'm not familiar with JS. Also, it can be a complex structure like list of objects with other objects inside. `console.log` would solve it in one-shot as "ok, give me a representation of this thing".

Another case that I personally faced is I want to test that `console.log` works in my framework. It's a rare case (who else and for what wants to make a wrapper for `console`?) but so.

@agnivade, right, there is no direct filesystem access from the browser VM. It breaks a lot of things: examples, coverage, maybe benchmarks. The thing is we can use something instead. Stdout or even open TCP port and send data onto it.

**Comment by orsinium** [comment]
> I have created an issue on puppetteer, but its not being worked on yet.

Great! Let's link it here:
https://github.com/puppeteer/puppeteer/issues/5210

**Comment by Gregory-Ledray** [comment]
With regards to console.log, console.log is working in the example I posted.

If all you want is to transfer complex objects you can use [JSON.stringify on the Javascript object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) in Javascript, transfer it over, and then Unmarshal in Go. Yes, it's wildly inefficient. But it'll work and it's well supported. My understanding of how to make such copies efficient for large objects is based on what works well for web workers, which is an older problem. I think web workers are currently the best way to multithread WASM code too (I believe that's what Rust is doing), which is part of why they're relevant. Efficient copying for web workers seems to come down to keeping large objects encoded as ArrayBuffer all the time - have it encoded that way when it's coming from the web server, and then only decode whatever parts of the object you need at any given time so it's easy to pass it, or subsets of it, around. I have never found a general solution for that, but perhaps we should develop one in a language which allows strict control of memory, like Rust. Of course then we also need to allow Rust and Go to interoperate in WASM, which is a different problem.

More info on how the browser clones objects: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

And multithreading: https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html
https://www.sitepen.com/blog/using-webassembly-with-web-workers/

**Comment by Gregory-Ledray** [comment]
Anyway, this seems to be pretty off-topic. You might also consider asking questions like this on Slack - https://invite.slack.golangbridge.org/ - at #webassembly

And closing this issue.

**Comment by orsinium** [comment]
Well,  `JSON.stringify` works for me. Anyway, examples mechanism will work after fixing https://github.com/puppeteer/puppeteer/issues/5210, if I understand correctly. At least, code coverage also depends on writing files. Thank you.

**Comment by orsinium** [comment]
NB: code that causes the issue is already a dirty hack to make examples work on nodejs:
https://github.com/golang/go/blob/dff55c1f7605294568ae7e00b09ef8935dbedf3b/src/testing/run_example_js.go#L19
However, it's not enough to make it work with headless chromium.

**Comment by agnivade** [comment]
Thanks for finding the pupeteer issue. I am on vacation so dont have much laptop access.

**Comment by orsinium** [comment]
Have a good vacation. Take a rest from Github as well, there is nothing urgent in open source :)
