### ISSUE TITLE
`could not dial` errors on the latest Chrome on GitHub Actions

### ISSUE THREAD

**Issue by hajimehoshi** [agnivade/wasmbrowsertest#22]
https://github.com/hajimehoshi/ebiten/runs/2203141403?check_suite_focus=true

I saw a lot of `[wasmbrowsertest]: 2021/03/26 15:45:06 main.go:158: could not dial "ws://127.0.0.1:32959/devtools/browser/***": EOF` errors and sometimes the test failed. This didn't happen 1 or 2 days ago. Do you have any insights? Thanks.

**Comment by hajimehoshi** [comment]
It looks like this happens only on Ubuntu.

**Comment by hajimehoshi** [comment]
This might be related to https://github.com/actions/virtual-environments/issues/2967

**Comment by agnivade** [comment]
Yeah, seems like that's the issue. This is the root cause I believe:

```
chrome failed to start:
mkdir: cannot create directory ‘/run/user/1001’: Permission denied
```

The `could not dial` error seems to be the websocket connection that drives the chromedp protocol.

**Comment by hajimehoshi** [comment]
Thank you for clarifying. As this is not wasmbrowsertest's responsibility, let me close this.
