### ISSUE TITLE
please enable discussions on this repo

### ISSUE THREAD

**Issue by unicomp21** [agnivade/wasmbrowsertest#27]

**Comment by agnivade** [comment]
Is there anything you have in mind that cannot be discussed in issues? I don't mind enabling discussions, but IMO it's easier to keep everything in issues unless there are super-large proposals to discuss that get hard to track via an issue.

**Comment by unicomp21** [comment]
Not yet, just don't think this is the appropriate place for me to ask questions if I'm trying to understand something.

**Comment by agnivade** [comment]
No worries, please feel free to create issues to ask questions. :)

**Comment by unicomp21** [comment]
will do, thx!
