### ISSUE TITLE
Error: command line too long

### ISSUE THREAD

**Issue by realPy** [agnivade/wasmbrowsertest#30]
Hi ,
Thanks for your project.
I would like to migrate my test from travis to github actions and the test failed with "Error: command line too long"
Any idea why  this error happening? I sucessfull run test on a ubuntu:latest container , the problem is on the github actions (maybe the go install is not on the default location)

**Comment by realPy** [comment]
you can check here:

https://github.com/realPy/hogosuru/runs/4054932859?check_suite_focus=true

On local no problem

**Comment by agnivade** [comment]
This is a regression (https://github.com/golang/go/issues/49011) on newer Go releases, which is backported now. It should be available in 1.17.3 and 1.16.10.

If your test does not depend on any environment variables, a good way would be to just wipe all of them before running your test.

**Comment by realPy** [comment]
Hello @agnivade you are right and it work i will share you my conf for other user want to use github action ;)

**Comment by realPy** [comment]
For people want to use with github action, create in ci.yml in .github/workflows/ with the content:


`on: [push, pull_request]
name: Unit Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install chrome
      uses: browser-actions/setup-chrome@latest
    - name: Run chrome headless
      run:  google-chrome --no-sandbox --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 &
    - name: Install dep
      run: go install github.com/agnivade/wasmbrowsertest@latest
    - name: Setup wasmexec
      run: mv $(go env GOPATH)/bin/wasmbrowsertest $(go env GOPATH)/bin/go_js_wasm_exec
    - name: Keep only env useful
      run: echo "GOPATH=$(go env GOPATH) GOCACHE=$(go env GOCACHE) GOROOT=$(go env GOROOT) PATH=$(echo $PATH)" >/opt/.env    
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run:  env -i $(cat /opt/.env) GOOS=js GOARCH=wasm go test ./...
`

**Comment by agnivade** [comment]
It would be great if you would like to send a PR to add a section in the README pointing to your file. :)

**Comment by realPy** [comment]
I'll do
