### ISSUE TITLE
cross browser testing

### ISSUE THREAD

**Issue by joeblew99** [agnivade/wasmbrowsertest#32]
this is designed for chrome.

anyone have any ideas about if we can extend this for Edge and Safari ?

**Comment by joeblew99** [comment]
rust seem to have something to cope with that: https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/browsers.html

**Comment by agnivade** [comment]
Yes, this is purely using the Chrome driver APIs. Happy to see a proposal supporting other browsers as well.

**Comment by realPy** [comment]
@agnivade i think we can do it .
Your main problem is "catching error" in console right?
Have you think to inject some syscall replacement and use Javascript Reflection to handle error?
This is something i do in hogosuru:

https://github.com/realPy/hogosuru/blob/develop/baseobject/baseobject.go

Take a look or contact me i have some idea to to this.

**Comment by agnivade** [comment]
I'd really prefer to avoid doing call injections and reflection to achieve this. I'd rather this be supported properly in the driver.

**Comment by agnivade** [comment]
Closing this. Nothing has changed since last post.
