### ISSUE TITLE
Tests flake when a callback is called after the test finishes

### ISSUE THREAD

**Issue by paralin** [agnivade/wasmbrowsertest#60]
It seems that just after a test finishes, if a callback is called after the Go runtime has exited, an error will be thrown and the test is marked as failed.

Instead, if the test passes, wasmbrowsertest should ignore any failures that occur after the test passed.

Example:

```
PASS
TypeError: Cannot read properties of undefined (reading 'exports')
    at syscall/js.valueCall (http://127.0.0.1:52353/wasm_exec.js:361:24)
    at http://127.0.0.1:52353/test.wasm:wasm-function[1619]:0x146f71
    at http://127.0.0.1:52353/test.wasm:wasm-function[1618]:0x146973
    at http://127.0.0.1:52353/test.wasm:wasm-function[1669]:0x150ea8
    at http://127.0.0.1:52353/test.wasm:wasm-function[1665]:0x14f9be
    at http://127.0.0.1:52353/test.wasm:wasm-function[1907]:0x19548a
    at http://127.0.0.1:52353/test.wasm:wasm-function[1944]:0x19c4d6
    at http://127.0.0.1:52353/test.wasm:wasm-function[3991]:0x402887
    at http://127.0.0.1:52353/test.wasm:wasm-function[1382]:0x12875c
    at http://127.0.0.1:52353/test.wasm:wasm-function[1387]:0x12881d
exit with status 1
FAIL
```

The error also can look like this:

```
PASS
http://127.0.0.1:63567/wasm_exec.js:542:10 Uncaught
Error: Go program has already exited
    at globalThis.Go._resume (http://127.0.0.1:63567/wasm_exec.js:543:11)
    at RTCDataChannel.<anonymous> (http://127.0.0.1:63567/wasm_exec.js:556:8)
context canceled
```

**Comment by agnivade** [comment]
Thanks, do you have a reproducer by any chance that I can use?

**Comment by paralin** [comment]
I will try to put one together. In this case I believe the code had run some IndexedDB queries with https://github.com/aperturerobotics/go-indexeddb and then the onsuccess callback was being called after the program had exited.

A possible test case would be to spam callbacks to the Go runtime and then succeed the test. The callback should be able to fire and call into Go wasm (which causes an error in the browser as well) just after the test exits, reproducing the issue.

**Comment by agnivade** [comment]
@paralin - Just checking if you were able to find some time on this?

**Comment by paralin** [comment]
I haven't had a chance yet but will try to get to it soon. Try just making a test that fires a callback in 10ms and then end the test successfully after 9ms. Should work if the callback fires just after the test ends.

**Comment by paralin** [comment]
Here is a slightly different error that also happens just after a test succeeds. I have seen both this error and the "Go program has already exited" errors. https://github.com/aperturerobotics/bifrost/actions/runs/9881158616/job/27291318234#step:14:1228

**Comment by paralin** [comment]
Another example: https://github.com/aperturerobotics/util/actions/runs/9881287652/job/27291736799#step:14:282

**Comment by hajimehoshi** [comment]
I've seen the same issue.

```
http://127.0.0.1:35499/wasm_exec.js:535:10 Uncaught
Error: Go program has already exited
    at globalThis.Go._resume (http://127.0.0.1:35499/wasm_exec.js:536:11)
    at http://127.0.0.1:35499/wasm_exec.js:264:14
context canceled
```

https://github.com/hajimehoshi/ebiten/actions/runs/9927011041/job/27421409861

**Comment by agnivade** [comment]
Thanks Hajime san. This is on my mind. Work has been a bit busy these days.

**Comment by hajimehoshi** [comment]
This can mitigate the issue by adding a sleep like this:

```go
func TestMain(m *testing.M) {
	code := m.Run()
	time.Sleep(100 * time.Millisecond)
	os.Exit(code)
}
```

**Comment by agnivade** [comment]
@hajimehoshi @paralin - I am trying with this:

```go
func TestCallback(t *testing.T) {
	js.Global().Call("setTimeout", js.FuncOf(func(js.Value, []js.Value) interface{} {
		t.Log("hey there")
		return nil
	}), 1000)
	t.Log("done")
}
```

but unable to reproduce the issue. What am I doing wrong?

**Comment by agnivade** [comment]
Aha nvm, I am able to repro now. The thing is that the timeout needs to fire between the small window when the test has exited, but the browser hasn't yet unloaded.

Repro case:

```go
func TestCallback(t *testing.T) {
	js.Global().Call("setInterval", js.FuncOf(func(js.Value, []js.Value) interface{} {
		t.Log("hey there")
		return nil
	}), 5)

	t.Log("done")
}
```

**Comment by hajimehoshi** [comment]
Thanks!
